

# REST Client allows you to send HTTP request and view the response in Visual Studio Code directly.


@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}


# POST http://{{host}}/users/register HTTP/1.1
# content-type: application/json

# {
#   "user_name": "Mitchell",
#   "password": "12345678"
# }



# POST http://{{host}}/users/login HTTP/1.1
# content-type: application/json

# {
#   "user_name": "Mitchell",
#   "password": "12345678"
# }

# PATCH  http://{{host}}/users HTTP/1.1
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA3NzcyMjQsImV4cCI6MTY1MDg2MzYyNH0.P3Ud8-bE748pLeponjbDtSomkmb5kVRFa90L7P6abXM

# {
#   "password": "6666666"
# }

POST http://{{host}}/goods/upload HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA3NzcyMjQsImV4cCI6MTY1MDg2MzYyNH0.P3Ud8-bE748pLeponjbDtSomkmb5kVRFa90L7P6abXM