

# REST Client allows you to send HTTP request and view the response in Visual Studio Code directly.


@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}


# POST http://{{host}}/users/register HTTP/1.1
# content-type: application/json

# {
#   "user_name": "Mitchell",
#   "password": "12345678"
# }



# POST http://{{host}}/users/login HTTP/1.1
# content-type: application/json

# {
#   "user_name": "Mitchell",
#   "password": "12345678"
# }